# Generated by Django 2.1.4 on 2018-12-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
